.github/workflows/build.yml
=> Deploy Algolia.

docs/FAQs.md, docs/contributing/_category_.json, docs/contributing/contributing-to-nmrxiv.mdx, docs/license.md
=> Add FAQ's update contribution section and update copyright to reflect 2022

docs/introduction/data/ontologies.md
=> fix: restructure ontologies page and add the schemas and ontology component

docs/contributing/contributors.mdx
=> fix: add contributors

docs/developer-guides/API.md
=> fix: fix links

docs/introduction/data/schemas.md
=> fix: restructure schema page - add Bioschemas

docs/workshops.md
=> feat: fill workshops page

docs/community/_category_.json, docs/community/media-kit.md, docs/community/training.md, docs/community/workshops.md, docs/training.md
=> feat: add community folder

docs/developer-guides/installation/linux.md, docs/developer-guides/installation/mac.md, docs/developer-guides/installation/windows.md
=> fix: update installation pages

docs/contributing/nmrxiv-docs.mdx
=> fix: add branching

docs/advanced-guides/nmr-repositories/background.md
=> fix: expand background page

docs/submission-guides/data-model/project.md, docs/submission-guides/data-model/sharing.md
=> fix: update shar

docs/submission-guides/submission/molecular-assignments.md, docs/submission-guides/submission/sample-details.md, docs/submission-guides/submission/spectra.md
=> fix: fill spectra page

docs/miscellaneous/_category_.json, docs/miscellaneous/shortcuts.md, docs/miscellaneous/tour.md, docs/submission-guides/spectra.md, docs/submission-guides/submission/shortcuts.md, docs/submission-guides/submission/tour.md
=> fix: add miscellaneous section

docs/FAQs.md, docs/developer-guides/installation/ubuntu.md, docs/submission-guides/registration.md, docs/submission-guides/submission/folder-structure.md
=> fix: update FAQs

docs/introduction/intro.md
=> fix: update into page

docs/developer-guides/deployment/environment.md
=> no message

docs/FAQs.md, docs/contributing/nmrxiv-docs.mdx
=> fix: add citation conventions

docs/submission-guides/data-model/sharing.md, docs/submission-guides/data-model/study.md
=> fix:  update sharing

docs/submission-guides/submission/editor.md
=> fix:  update structure editor

docs/advanced-guides/nmr-repositories/organism.md, docs/advanced-guides/nmr-repositories/part.md
=> feat:  add organism part page

docs/advanced-guides/nmr-repositories/part.md, docs/advanced-guides/nmr-repositories/variant.md
=> feat add variant page
